RentaAutos/RentaAutos/config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :users
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/new'

  get 'welcome/index'

  resources :appointments
  resources :pets
  resources :doctors

  root 'welcome#index'

end

RentaAutos/RentaAutos/app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :pet
=begin
  validates :date, presence: true
  validate :date_in_past , :on => :create
  validates :pet, presence: true
  validates :customer, presence: true
  validates :reason, presence: true  
=end

end

RentaAutos/RentaAutos/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:create, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
    
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
	puts "===================="
    puts "#{appointment_params}"
	puts "===================="
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Renta Creada Correctamente.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Renta Actualizada Correctamente.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Renta Eliminada Correctamente.' }
      format.json { head :no_content }
    end
  end

  def link_to_if_with_block condition, options, html_options={}, &block
     if condition
       link_to options, html_options, &block
     else
       capture &block
     end
   end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:pet_name, :doctor_name, :reason, :appointment_date, :doctor_id, :pet_id)
    end
end

RentaAutos/RentaAutos/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

RentaAutos/RentaAutos/app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Seleciona el auto" %><br>
    <%= f.collection_select :pet_id, Pet.order(:name),:id,:name, include_blank: true %>

	
  </div>
  <div class="field">
    <%= f.label "Seleciona Cliente"%><br>
    <%= f.collection_select :doctor_id, Doctor.order(:name),:id,:name, include_blank: true %>

  </div>
  <div class="field">
    <%= f.label :Razon %><br>
    <%= f.text_area :reason %>
  </div>
  <div class="field">
    Fecha de renta<br>
    <%= f.date_select :appointment_date %>
  </div>
  
  <div class="field">
    <%#= f.label :doctor_id %><br>
    <%#= f.text_field :doctor_id %>
  </div>
  <div class="field">
    <%#= f.label :pet_id %><br>
    <%#= f.text_field :pet_id %>
  </div>
  
  <div class="actions">
    <%= f.submit :Aceptar%>
  </div>
<% end %>

RentaAutos/RentaAutos/app/views/appointments/edit.html.erb
<h1>Editar Renta</h1>

<%= render 'form' %>

<%= link_to 'Ver', @appointment %> |
<%= link_to 'Atras', appointments_path %>

RentaAutos/RentaAutos/app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Rentas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre Auto</th>
      <th>Nombre Cliente</th>
      <th></th>
      <th>Fecha de Renta</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= Pet.get_name(appointment.pet_id) %></td>
        <td><%= Doctor.get_name(appointment.doctor_id) %></td>
        <td><%= appointment.doctor_name %></td>
        <td><%= appointment.reason %></td>
        <td><%= appointment.appointment_date %></td>

        <td><%= link_to 'Ver', appointment %></td>
        <td><%= link_to 'Editar', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Eliminar', appointment, method: :delete, data: { confirm: 'Estas Seguro de eliminar el Cliente?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Renta', new_appointment_path %>

RentaAutos/RentaAutos/app/views/appointments/new.html.erb
<h1>Nueva Renta</h1>

<%= render 'form' %>

<%= link_to 'Atras', appointments_path %>

RentaAutos/RentaAutos/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre Cliente:</strong>
  <%= Pet.get_name(@appointment.pet_id) %>

</p>

<p>
  <strong>Nombre Auto:</strong>
  <%= Doctor.get_name(@appointment.doctor_id) %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @appointment.reason %>
</p>

<p>
  <strong>Fecha de alta:</strong>
  <%= @appointment.appointment_date %>
</p>


<%= link_to 'Editar', edit_appointment_path(@appointment) %> |
<%= link_to 'Atras', appointments_path %>